# Installation dependencies and settings
# -----------------------------------------------------------------------------
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"

brew "mas"

# Programming languages
# -----------------------------------------------------------------------------
brew "go"
brew "node"
brew "python@3.11"
brew "lua"

# CLI Tools or other end-use software
# -----------------------------------------------------------------------------
brew "age"
brew "1password-cli"
brew "sops"
brew "ansible", link: false
brew "fzf"
brew "git"
brew "jj" 
brew "helm"
brew "istioctl"
brew "k3d"
brew "kubernetes-cli"
brew "minikube"
brew "neovim"
brew "parallel"
brew "qemu"
brew "ripgrep"
brew "stow"
brew "terraform"
brew "tmux"
brew "watch"
brew "wget"
cask "drawio"

# Dependencies for programming languages and the like
# -----------------------------------------------------------------------------
brew "libssh"
brew "rustup-init"
brew "delve"

## GUI Apps 
## -----------------------------------------------------------------------------
cask "rectangle"
cask "qmk-toolbox"

## Fonts
## -----------------------------------------------------------------------------
cask "font-hack-nerd-font"


## VSCode 
## ------------------------------------------------------------


